import numpy as np
import qutip as qt
import matplotlib.pyplot as plt

# ==================== Parameters ====================
N = 10                         # Fock space truncation
eta = 0.8                      # Evolution time
xvec = np.linspace(-5, 5, 120)

# ==================== GKSL Generator with High χ(L) ====================
# Strong coherent drive (high coherence-generating power)
H = (qt.create(N) + qt.destroy(N)) * 1.5

# Very weak damping (so coherence can build up)
c_ops = [np.sqrt(0.05) * qt.destroy(N)]

L = qt.liouvillian(H, c_ops)

# ==================== Initial Non-Classical State ====================
# Start in Fock state |1> (has negative Wigner regions)
rho0 = qt.ket2dm(qt.basis(N, 1))

# ==================== Evolve ====================
result = qt.mesolve(L, rho0, [0, eta], c_ops=[], e_ops=[])
rho_final = result.states[-1]

# ==================== Wigner Functions ====================
W0 = qt.wigner(rho0, xvec, xvec, g=2)
W  = qt.wigner(rho_final, xvec, xvec, g=2)

# ==================== Plot ====================
fig, axes = plt.subplots(1, 2, figsize=(13, 5.5))

# Initial
im0 = axes[0].contourf(xvec, xvec, W0, 100, cmap='RdBu_r', vmin=-0.4, vmax=0.4)
axes[0].set_title("Initial: Fock state |1⟩ (t=0)\n(Non-classical, negative regions)", fontsize=11)
axes[0].set_xlabel("Re(α)")
axes[0].set_ylabel("Im(α)")
plt.colorbar(im0, ax=axes[0], label="Wigner function W(α)")

# Final
im1 = axes[1].contourf(xvec, xvec, W, 100, cmap='RdBu_r', vmin=-0.4, vmax=0.4)
axes[1].set_title(f"After evolution under strong drive (t={eta})\n(Coherence generated by GKSL generator)", fontsize=11)
axes[1].set_xlabel("Re(α)")
axes[1].set_ylabel("Im(α)")
plt.colorbar(im1, ax=axes[1], label="Wigner function W(α)")

plt.suptitle("Wigner Function Evolution — Relevance to Coherence Generation (χ(L) > 0)", fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('/home/workdir/artifacts/wigner_coherence_generation.png', dpi=160)
plt.show()

# ==================== Wigner Negativity ====================
negativity = np.sum(np.abs(W[W < 0])) * (xvec[1]-xvec[0])**2
print(f"Integrated Wigner negativity after evolution: {negativity:.4f}")
print("(Higher negativity generally correlates with stronger coherence effects)")
